name: GitHub-Profile-3D-Contrib

on:
  schedule: # 01:00 CST == 07:00 UTC (MILITARY TIME)
    - cron: "0 07 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: makbaran/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME: makbaran
          SETTING_JSON: conf/github-profile-3d-contrib.json
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
           if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add -A .
          git commit -m "generated"
          git push
